name: Executar Selenium Diariamente

on:
  schedule:
    - cron: "0 15 * * *" # Executa todos os dias às 03:00 UTC (ajuste conforme necessário)
  workflow_dispatch: # Permite execução manual

jobs:
  selenium_job:
    runs-on: ubuntu-latest # Máquina virtual com Ubuntu

    steps:
      # Passo 1: Checkout do repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # Passo 2: Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.13" # Ajuste conforme necessário

      # Passo 3: Instalar dependências do projeto
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 4: Carregar variávies de ambiente
      - name: Usar Secret como Variável de Ambiente
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          KEYWORDS: ${{ secrets.KEYWORDS }}

      # Passo 5: Executar o script Selenium
      - name: Executar script Selenium
        run: python main.py
