name: Executar Selenium Diariamente

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  selenium_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar script Selenium
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          KEYWORDS: ${{ secrets.KEYWORDS }}
        run: python main.py

      - name: Listar arquivos
        run: ls -alh
